# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Ngram-LanguageDetermine
version:      0.01
version_from: lib/Text/Ngram/LanguageDetermine.pm
installdirs:  site
requires:
    Carp:                          0
    List::Util:                    0
    Params::Check:                 0
    Storable:                      0
    Test::Simple:                  0.44
    Text::Ngram:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
